language: elixir
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.7.4
  - 1.8.2
  - 1.9.4
  - 1.10.3
otp_release:
  - 21.3
  - 22.3
jobs:
  include:
    - elixir: '1.10.3'
      otp_release: '23.0'
script:
  - bin/test.sh
